DROP DATABASE IF EXISTS proyectoFarmacia;
CREATE DATABASE proyectoFarmacia;
USE proyectoFarmacia;

CREATE TABLE TB_ROLES (
    ID_ROL INT PRIMARY KEY,
    DESCRIPCION CHAR(1) NOT NULL
);

INSERT INTO TB_ROLES(ID_ROL,DESCRIPCION)
VALUES
(1,'A'),
(2,'F'),
(3,'C');

CREATE TABLE TB_ESTADO(
	ID_ESTADO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(15) NOT NULL
);

INSERT INTO TB_ESTADO(ID_ESTADO, DESCRIPCION)
VALUES
(1,'ACTIVO'),
(2,'ELIMINADO');

CREATE TABLE TB_USUARIOS (
	ID_USUARIO INT PRIMARY KEY auto_increment,
    TIPO_DOCUMENTO VARCHAR(3) CHECK(TIPO_DOCUMENTO IN('DNI','CE','PAS')),
    DOCUMENTO VARCHAR(12) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    CLAVE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50) NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    ROL INT DEFAULT 3,
    ESTADO INT DEFAULT 1,
    FOREIGN KEY (ROL) REFERENCES TB_ROLES(ID_ROL),
    FOREIGN KEY(ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE TABLE TB_FARMACEUTICOS (
    ID_FARMACEUTICO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    TIPO_DOCUMENTO VARCHAR(3) CHECK(TIPO_DOCUMENTO IN('DNI','CE','PAS')),
    DOCUMENTO VARCHAR(12) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50) NULL,
    ESTADO INT DEFAULT 1,
    FOREIGN KEY (ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE TABLE TB_PROVEEDORES (
    ID_PROVEEDOR INT PRIMARY KEY AUTO_INCREMENT,
    RUC CHAR(11) NOT NULL CHECK (RUC REGEXP '^20[0-9]{9}$'),
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
    TELEFONO CHAR(15) NOT NULL,
    DIRECCION VARCHAR(80) NOT NULL,
    ESTADO INT DEFAULT 1,
    FOREIGN KEY (ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE TABLE TB_MEDICAMENTOS (
	ID_MEDICAMENTO CHAR(5) PRIMARY KEY,
    IMAGEN MEDIUMBLOB NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK_ACTUAL INT NOT NULL,
    STOCK_MAXIMO INT NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    ESTADO INT DEFAULT 1,
    DESCRIPCION TEXT NULL,
    ID_PROVEEDOR INT,
    PREESCRIPCION CHAR(3) CHECK (PREESCRIPCION IN('SRM','CRM')),
    FOREIGN KEY(ID_PROVEEDOR) REFERENCES TB_PROVEEDORES(ID_PROVEEDOR),
	FOREIGN KEY(ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE TABLE TB_ORDENES_COMPRA (
    ID_ORDEN INT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'COMPLETADA' 
        CHECK (ESTADO IN ('PENDIENTE', 'COMPLETADA', 'CANCELADA')),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS (ID_USUARIO)
);

CREATE TABLE TB_DETALLE_COMPRA (
    ID_ORDEN INT,
    ID_MEDICAMENTO CHAR(5) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(ID_ORDEN,ID_MEDICAMENTO),
    FOREIGN KEY (ID_ORDEN) REFERENCES TB_ORDENES_COMPRA(ID_ORDEN),
    FOREIGN KEY (ID_MEDICAMENTO) REFERENCES TB_MEDICAMENTOS(ID_MEDICAMENTO)
);